FROM python:3.10-slim

WORKDIR /app/frontend

COPY frontend/ /app/frontend/

RUN pip install --upgrade pip
RUN pip install -r requirements.txt

EXPOSE 8501

ENV STREAMLIT_SERVER_HEADLESS=true
ENV STREAMLIT_SERVER_PORT=8501
ENV STREAMLIT_SERVER_ADDRESS=0.0.0.0
ENV PYTHONPATH=/app

CMD ["streamlit", "run", "app.py"]